@PORT = 6969
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NTM0MmU4MGFkNTM1NjBlZDVmZGEyOSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTczMzgwODY5MywiZXhwIjoxNzMzODEyMjkzfQ.0_1PK5qirVVRk8ogLx_bTADf-P-Kha5d2t88TxlmoQI

@connection = https

### Get all movies -> 200
GET {{connection}}://localhost:{{PORT}}/movies
Authorization: Bearer {{token}}

### Get movie by ID -> 200
GET {{connection}}://localhost:{{PORT}}/movies/3
Authorization: Bearer {{token}}

### Attempt to get movie with Invalid ID -> 404
GET {{connection}}://localhost:{{PORT}}/movies/200
Authorization: Bearer {{token}}

### Add new movie -> 201
POST {{connection}}://localhost:{{PORT}}/movies
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Tenet",
  "director": "Christopher Nolan",
  "year": 2020
}

### Attempt to add movie with invalid fields -> 400
POST {{connection}}://localhost:{{PORT}}/movies
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Mad Max: Fury Road",
  "director": "Rupert Miller",
  "year": 1015
}

### Attempt to add movie with missing fields -> 400
POST {{connection}}://localhost:{{PORT}}/movies
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Super New Real Movie",
}

### Delete movie -> 204
DELETE {{connection}}://localhost:{{PORT}}/movies/5
Authorization: Bearer {{token}}

### Attempt to delete non-existant movie -> 404
DELETE {{connection}}://localhost:{{PORT}}/movies/2000
Authorization: Bearer {{token}}

### Update a movie -> 200
PUT {{connection}}://localhost:{{PORT}}/movies/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Oppenheimer",
  "director": "Christopher Nolan",
  "year": 2023
}

### Attempt to update movie with invalid fields -> 400
PUT {{connection}}://localhost:{{PORT}}/movies/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Oppenheimer",
  "director": "Christopher Nolan",
  "year": 3023
}

### Attempt to update non-existant movie -> 404
PUT {{connection}}://localhost:{{PORT}}/movies/2000
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Oppenheimer",
  "director": "Christopher Nolan",
  "year": 2023
}

### Test undefined route -> 404
GET {{connection}}://localhost:{{PORT}}/directors
Authorization: Bearer {{token}}

### Test query
GET {{connection}}://localhost:{{PORT}}/movies?director=Chris
Authorization: Bearer {{token}}

### Login Test - Valid Credentials [admin]
POST {{connection}}://localhost:{{PORT}}/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

### Login Test - Valid Credentials [regular]
POST {{connection}}s://localhost:{{PORT}}/auth/login
Content-Type: application/json

{
  "username": "user",
  "password": "password"
}

### Login Test - Invalid Username
POST {{connection}}://localhost:{{PORT}}/auth/login
Content-Type: application/json

{
  "username": "not_a_user",
  "password": "admin123"
}

### Login Test - Invalid Password
POST {{connection}}://localhost:{{PORT}}/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "wrong_password"
}

### Register Test
POST {{connection}}://localhost:{{PORT}}/auth/register
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123",
  "role": "admin"
}

### Test WebSocket Conenction
